/* =========================================================
   CARDÁPIO — Ursulão Pizzas
   Para alterar preços ou sabores, edite apenas este arquivo.
   Formato: [nome, ingredientes, preço Grande, preço Broto]
   ========================================================= */

const CARDAPIO = {
  salgadas: [
    ["Abobrinha", "Catupiry, abobrinha e parmesão", 102, 72],
    ["Abobrinha 2", "Mussarela, abobrinha e parmesão", 102, 72],
    ["Alho e Óleo", "Molho de tomate, alho frito e parmesão", 94, 73],
    ["Aliche", "Molho de tomate, aliche e parmesão", 104, 73],
    ["Alichela", "Mussarela, filés de aliche e molho de tomate", 104, 73],
    ["Americana 1", "Peito de peru defumado, palmito, catupiry e bacon", 116, 81],
    ["Americana 2", "Peito de peru defumado, palmito, mussarela e bacon", 112, 78],
    ["Atum 1", "Atum sólido e cebola", 98, 69],
    ["Atum 2", "Atum sólido, palmito e cebola", 104, 73],
    ["Bacon 1", "Mussarela e bacon fatiado", 102, 72],
    ["Bacon 2", "Catupiry e bacon fatiado", 105, 73],
    ["Baiana", "Calabresa moída, pimenta, cebola e mussarela", 98, 69],
    ["Bauru", "Presunto, tomate, mussarela e azeitonas", 90, 63],
    ["Berinjela 1", "Molho extra, berinjela e parmesão", 98, 69],
    ["Berinjela 2", "Mussarela, berinjela e parmesão", 98, 69],
    ["Brasileira", "Presunto, palmito, milho, tomate e mussarela", 102, 72],
    ["Brócolis 1", "Brócolis refogado e mussarela", 98, 69],
    ["Brócolis 2", "Brócolis refogado e catupiry", 102, 72],
    ["Brócolis 3", "Brócolis refogado, palmito, milho verde e bacon", 104, 73],
    ["Búfala", "Tomate seco, manjericão, mussarela de búfala e parmesão", 104, 73],
    ["Caipira 1", "Peito de frango desfiado, palmito, ovos e mussarela", 102, 72],
    ["Caipira 2", "Peito de frango desfiado, palmito, ovos e catupiry", 105, 74],
    ["Calabresa", "Calabresa fatiada e cebola", 62, 43],
    ["Calabria", "Calabresa fatiada, parmesão polvilhado e rúcula por cima", 98, 69],
    ["Catupiry", "Catupiry e azeitonas", 83, 58],
    ["Catu Calabresa", "Catupiry e calabresa fatiada", 98, 69],
    ["Catu Lombinho", "Lombo canadense fatiado e catupiry", 98, 69],
    ["Catu Moída", "Catupiry e calabresa moída", 98, 69],
    ["Carne Seca", "Carne seca desfiada, cebola e mussarela", 98, 69],
    ["Cinco Queijos", "Mussarela, provolone, parmesão, gorgonzola e catupiry", 104, 73],
    ["Cris", "Palmito, champignon temperado, milho verde e catupiry", 98, 69],
    ["Dois Queijos", "Mussarela e catupiry", 93, 65],
    ["Escarola", "Escarola refogada, mussarela e bacon", 98, 69],
    ["Espanhola", "Atum sólido, palmito, milho verde, cebola e mussarela", 102, 71],
    ["Frango 1", "Peito de frango desfiado e catupiry", 102, 72],
    ["Frango 2", "Peito de frango desfiado e mussarela", 102, 72],
    ["Frango 3", "Peito de frango desfiado, catupiry e bacon", 102, 72],
    ["Franguinho", "Peito de frango desfiado, catupiry e milho verde", 102, 72],
    ["Holandesa", "Catupiry, calabresa moída e parmesão", 102, 72],
    ["Italiana", "Mussarela, molho de tomate, alho frito e parmesão", 102, 72],
    ["Marguerita", "Mussarela, molho de tomate e manjericão", 88, 62],
    ["Milho Verde 1", "Mussarela e milho verde", 90, 63],
    ["Milho Verde 2", "Catupiry e milho verde", 92, 65],
    ["Mineirinha", "Lombo, banana, mussarela e bacon picado", 102, 72],
    ["Mista 1", "Mussarela e calabresa fatiada", 92, 65],
    ["Mista 2", "Calabresa fatiada e mussarela", 87, 61],
    ["Moidinha", "Calabresa moída, pimenta e cebola", 92, 65],
    ["Montana", "Mussarela, tomate fatiado, cebola, calabresa fatiada, ovos e bacon", 100, 70],
    ["Mussarela", "Mussarela e tomate fatiado", 66, 46],
    ["Napolitana", "Mussarela, tomate fatiado e parmesão", 102, 72],
    ["Palmito 1", "Mussarela e palmito", 102, 72],
    ["Palmito 2", "Catupiry e palmito", 104, 73],
    ["Pepperone 1", "Mussarela, salame pepperone, champignon temperado e parmesão", 115, 80],
    ["Pepperone 2", "Mussarela de búfala, salame pepperone, champignon temperado e parmesão", 123, 86],
    ["Peruana 1", "Atum sólido e mussarela", 102, 72],
    ["Peruana 2", "Atum sólido e catupiry", 102, 71],
    ["Picante", "Molho de tomate extra, calabresa fatiada, pimenta, erva-doce e parmesão", 102, 72],
    ["Portuguesa 1", "Presunto fatiado, cebola, ovos e mussarela", 98, 69],
    ["Portuguesa 2", "Presunto fatiado, cebola, ovos e catupiry", 99, 69],
    ["Quatro Queijos", "Mussarela, provolone, parmesão e catupiry", 102, 71],
    ["Romana", "Mussarela, tomate fatiado e aliche", 95, 67],
    ["Romanesca", "Catupiry, presunto, champignon e bacon", 104, 73],
    ["Rúcula 1", "Tomate seco, mussarela e rúcula", 108, 75],
    ["Rúcula 2", "Tomate seco, mussarela de búfala e rúcula", 116, 81],
    ["Saborosa", "Peito de peru, brócolis e catupiry", 102, 72],
    ["Siciliana", "Mussarela, champignon e bacon", 102, 72],
    ["Tio Sam 1", "Peito de peru defumado e catupiry", 102, 72],
    ["Tio Sam 2", "Peito de peru defumado e mussarela", 102, 72],
    ["Tio Sam 3", "Catupiry, peito de peru e parmesão", 102, 71],
    ["Toscana", "Calabresa moída, cebola e parmesão", 92, 64],
    ["Três Queijos", "Mussarela, provolone e catupiry", 92, 64],
    ["Trop Frango", "Mussarela, alho frito, peito de frango desfiado e filetes de catupiry", 102, 72],
    ["Trop Lombinho", "Mussarela, alho frito, lombo canadense e filetes de catupiry", 102, 72],
    ["Trop Palmito", "Mussarela, alho frito, palmito e filetes de catupiry", 102, 71],
    ["Trop Peru", "Mussarela, alho frito, peito de peru defumado e filetes de catupiry", 102, 72],
    ["Ursulão", "Presunto, palmito, pimenta, mussarela, tomate fatiado, bacon e parmesão", 102, 72],
    ["Vegetariana 1", "Escarola, tomate seco, palmito, champignon, milho verde, cebola e tomate", 102, 72],
    ["Vegetariana 2", "Escarola, tomate seco, palmito, tomate, mussarela de búfala e rúcula", 116, 81],
  ],
  doces: [
    ["Brigadeiro", "Chocolate ao leite, granulado e cereja marrasquino", 74, 52],
    ["Prestígio", "Chocolate ao leite, leite condensado e coco ralado", 74, 52],
    ["Banana 1", "Banana pré-assada, leite condensado, chocolate ao leite e canela", 74, 52],
    ["Banana 2", "Banana pré-assada, leite condensado, mussarela e canela", 74, 52],
    ["Moranguinho", "Chocolate ao leite e cobertura de morango", 74, 52],
    ["MMS", "Chocolate ao leite e cobertura de M&M's", 74, 52],
  ],
};

/* Selos opcionais exibidos nos cards */
const SELOS = {
  "Ursulão": "Da casa",
  "Pepperone 2": "Premium",
  "Marguerita": "Clássica",
  "Vegetariana 1": "Veggie",
  "Vegetariana 2": "Veggie",
};
